# Configuration

name: Database Generator
tasks:
- kind: template
  fileext: .go
  filename: schema
  source:
  - templates\schema.tmpl
  target: database
  template: schema
- kind: template
  fileext: .go
  source:
  - templates\repository.tmpl
  target: database
  template: repository
  filename: repository


