# Configuration

name: Database Generator
tasks:
- kind: template
  fileext: .go
  filename: schema
  source:
  - templates\schema.tmpl
  - templates\schematypes.tmpl
  target: database
  template: schema


